export const GET_PRODUCTS = "GET_PRODUCTS";
export const START_GET_PRODUCTS = "START_GET_PRODUCTS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const ADD_SHOPPING = "ADD_SHOPPING";
export const UPDATE_SHOPPING = "UPDATE_SHOPPING";
export const GET_SHOPPINGS = "GET_SHOPPINGS";
export const DELETE_SHOPPING = "DELETE_SHOPPING";
export const SHOPPING_ERROR = "SHOPPING_ERROR";
export const SHOPPING_EMPTY = 'SHOPPING_EMPTY';

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const GET_USER = "GET_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";
